name: inzeli
description: Inzeli MVP
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  qr_flutter: ^4.1.0
  app_links: ^6.1.2
  http: ^1.2.0
  audioplayers: ^6.5.1
  win32: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
supabase_flutter:
  path: <your-path-to-the-local-supabase-flutter-repo>/packages/supabase_flutter